/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import java.util.*;
import java.util.stream.Collectors;

public class Algorithm9_1_3 {

    public static void main(String[] args) throws Exception {

        Scanner scanner = new Scanner(System.in);
        String firstLine = scanner.nextLine();
        String secondLine = scanner.nextLine();

        List<String> firstList = Arrays.asList(firstLine.split(" "));
        List<String> secondList = Arrays.asList(secondLine.split(" "));

        int numOfMembers = Integer.parseInt(firstList.get(0));
        int totalAblility = Integer.parseInt(firstList.get(1));

        List<Integer> abilityOfMembers =
            secondList.stream().map(s -> Integer.parseInt(s)).collect(Collectors.toList());

        int myAbility = abilityOfMembers.get(0);
        List<List<Integer>> totalContainer = new ArrayList<>();
        int[] numOfCases = {0};

        abilityOfMembers.remove(0);

        sum(0,0,null,totalContainer,abilityOfMembers);

        totalContainer.forEach(l -> {
                int sum =
                    l.stream().reduce(0, Integer::sum) + myAbility;
                if (sum == totalAblility) {
                    numOfCases[0]++;
                }
            });

        if (myAbility == totalAblility) {
            numOfCases[0]++;
        }

        System.out.println(numOfCases[0]);

        scanner.close();
    }

    public static void sum(int i,
                           int l,
                           List<Integer> container,
                           List<List<Integer>> totalContainer,
                           List<Integer> abilityOfMembers) {

        if (i == abilityOfMembers.size()
            || l == abilityOfMembers.size()) {
            return;
        }

        if (container == null) {
            container = new ArrayList<>();
            container.add(abilityOfMembers.get(i));
            totalContainer.add(container);

            sum(i, l+1, container, totalContainer, abilityOfMembers);
            sum(i+1, l, null, totalContainer, abilityOfMembers);
        } else {
            if (i < l) {
                List<Integer> copyOfContainer = new ArrayList<>(container);
                copyOfContainer.add(abilityOfMembers.get(l));
                totalContainer.add(copyOfContainer);

                sum(i, l+1, copyOfContainer, totalContainer, abilityOfMembers);
            }

            sum(i, l+1, container, totalContainer, abilityOfMembers);
        }

    }

}
