/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.*;

public class Algorithm9_1_2 {

    public static void main(String[] args) throws Exception {

        Scanner scanner = new Scanner(System.in);
        String line = scanner.nextLine();
        double input = Double.parseDouble(line);
        double roundedInput =
            new BigDecimal(input).setScale(0, RoundingMode.FLOOR).doubleValue();

        if (roundedInput == 0) {
            System.out.println("Yes");
            scanner.close();
            return;
        } else if (roundedInput < 0) {
            System.out.println("No");
            scanner.close();
            return;
        }

        double result = Math.log(roundedInput) / Math.log(2);
        if (new BigDecimal(result).scale() > 0) {
            System.out.println("No");
        } else {
            System.out.println("Yes");
        }

        scanner.close();
    }
}
