/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import java.util.*;
import java.util.stream.Collectors;

public class Algorithm9_2_1 {

    public static void main(String[] args) throws Exception {

        Scanner scanner = new Scanner(System.in);
        String totalNumInput = scanner.nextLine();
        int totalNum = Integer.parseInt(totalNumInput);
        Map<Integer, List<Float>> idNPositions = new HashMap<>();

        int lower = 0;
        int higher = 1;
        double distance = -1d;

        for (int i = 0; i < totalNum; i++) {
            String positionInput = scanner.nextLine();
            List<Float> position =
                Arrays.asList(positionInput.split(" "))
                .stream()
                .map(s -> Float.parseFloat(s))
                .collect(Collectors.toList());

            if (i > 0) {
                for (int j = 0; j < i; j++) {
                    double tmpDistance =
                        calculateDistance(idNPositions.get(j).get(0),
                                          idNPositions.get(j).get(1),
                                          position.get(0),
                                          position.get(1));

                    if (tmpDistance > distance) {
                        distance = tmpDistance;
                        lower = j;
                        higher = i;
                    } else if (tmpDistance == distance) {
                        if (lower > j) {
                            lower = j;
                            higher = i;
                        }
                    }
                }

            }

            idNPositions.put(i, position);
        }

        System.out.println((lower+1) + " " + (higher+1));

        scanner.close();
    }

    public static double calculateDistance(float x1, float y1, float x2, float y2) {
        float xd = x1 - x2;
        float yd = y1 - y2;

        double distance = Math.sqrt(xd * xd + yd * yd);

        return distance;
    }
}
